site_name: TLPI 笔记
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/panxiao81/learn-tlpi
repo_name: panxiao81/learn-tlpi
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - README: index.md
  - 环境: environment-preparing.md
  - 第三章-系统编程概念: chap3.md
  - 第四章-文件 I/O：通用的 I/O 模型: chap4.md
  - 第五章-深入探究文件 I/O: chap5.md
  - 第六章-进程: chap6.md
  - 第七章-内存分配: chap7.md
  - 第八章-用户和组: chap8.md
  - 第九章-进程凭证: chap9.md
